export const CAROUSELGRAPHICS = [
    {
        id: 0,
        imgHero: "/assets/images/geoYellowV2.png",
        imgThumbnail: "/assets/images/colour3.png",
        title: "GEO\n NEON",
        descriptionCarousel: 'Striking neon and purple geo design.',
        specTitle: ['SIZE: ', 'MATERIAL:', 'DESIGN:',],
        specDescription: ['9"L" x 3"W x 0.5"D', 'RECYCLED PLASTIC', 'LAZER CUT'],
    },
    {
        id: 1,
        imgHero: "/assets/images/geoV2.png",
        imgThumbnail: "/assets/images/colour4.png",
        title: "GEO\n CLASSIC",
        descriptionCarousel: 'Classic red and blue geo design.',
        specTitle: ['SIZE: ', 'MATERIAL:', 'DESIGN:',],
        specDescription: ['9"L" x 3"W x 0.5"D', 'RECYCLED PLASTIC', 'LAZER CUT'],
    },
    {
        id: 2,
        imgHero: "/assets/images/zigzag1.png",
        imgThumbnail: "/assets/images/colour1.png",
        title: "MAZE\n INK",
        descriptionCarousel: 'Versatile ink blue and white design.',
        specTitle: ['SIZE: ', 'MATERIAL:', 'DESIGN:',],
        specDescription: ['9"L" x 3"W x 0.5"D', 'RECYCLED PLASTIC', 'ETCHED'],
    },
    {
        id: 3,
        imgHero: "/assets/images/zigzag2.png",
        imgThumbnail: "/assets/images/colour2.png",
        title: "MAZE\n CANDY",
        descriptionCarousel: 'Fun candy pink and white design.',
        specTitle: ['SIZE: ', 'MATERIAL:', 'DESIGN:',],
        specDescription: ['9"L" x 3"W x 0.5"D', 'RECYCLED PLASTIC', 'ETCHED'],
    },
    {
        id: 4,
        imgHero: "/assets/images/lighteningV1.png",
        imgThumbnail: "/assets/images/colour5.png",
        title: "LIGHTNING\n BRIGHT",
        descriptionCarousel: 'Two colour black and white design.',
        specTitle: ['SIZE: ', 'MATERIAL:', 'DESIGN:',],
        specDescription: ['9"L" x 3"W x 0.5"D', 'RECYCLED PLASTIC', 'PRINTED'],
    },
    {
        id: 5,
        imgHero: "/assets/images/lightening2V1.png",
        imgThumbnail: "/assets/images/colour6.png",
        title: "LIGHTNING\n NIGHT",
        descriptionCarousel: 'Two colour white and black design.',
        specTitle: ['SIZE: ', 'MATERIAL:', 'DESIGN:',],
        specDescription: ['9"L" x 3"W x 0.5"D', 'RECYCLED PLASTIC', 'PRINTED'],
    },
]