export const GRAPHICSTEXT = [
    {
        id: 0,
        size: 'large',
        img: "/assets/images/headerLargeV2.jpg",
        title: "EVERYTHING YOU WANT IN A~ PHONECASE AND MORE",
        link1: '/preorder',
        link1Name: 'PRE-ORDER',
        link2: 'videolink',
        link2Name: 'WATCH VIDEO',
        buttonSize:'large',
        buttonColor:'white',
        video:'/assets/images/customizeImagesFinalV1.gif'
    },
    {
        id: 1,
        size: 'large',
        img: "/assets/images/headerLargeCustomizeV1.jpg",
        title: "EXPRESS YOUR INDIVIDUALITY,~ CUSTOMIZE YOUR CHOICE",
        link1: '/preorder',
        link1Name: 'PRE-ORDER',
        buttonSize:'large',
        buttonColor:'goldWhite',
    },
    {
        id: 2,
        size: 'large',
        img: "/assets/images/headerLargeSustainabilityV1.jpg",
        title: "STYLE AND SUSTAINABILITY IN~ THE PALM OF YOUR HAND",
        link1: '/news/#Sustainability_id',
        link1Name: 'SUSTAINABILITY',
        buttonSize:'large',
        buttonColor:'whiteGold',
    },
    {
        id: 3,
        img: "/assets/images/headerSmallNews.jpg",
        title: "NEWS",
        link1: '/sustainability',
        link1Name: 'SUSTAINABILITY',
    },
    {
        id: 4,
        img: "/assets/images/preOrderheader.jpg",
        title: "PRE ORDER",
        link1: '/sustainability',
        link1Name: 'PRE ORDER',
    },
    {
        id: 5,
        img: "/assets/images/faqV1.jpg",
        title: "FAQ",
        link1: '/sustainability',
        link1Name: 'PRE-ORDER',
    },
]
