export const GRAPHICSTEXT_LOADING = 'GRAPHICSTEXT_LOADING';
export const GRAPHICSTEXT_FAILED = 'GRAPHICSTEXT_FAILED';
export const ADD_GRAPHICSTEXT = 'ADD_GRAPHICSTEXT';

export const TWOCOLUMNGRAPHICS_LOADING = 'TWOCOLUMNGRAPHICS_LOADING';
export const TWOCOLUMNGRAPHICS_FAILED = 'TWOCOLUMNGRAPHICS_FAILED';
export const ADD_TWOCOLUMNGRAPHICS = 'ADD_TWOCOLUMNGRAPHICS';

export const CAROUSELGRAPHICS_LOADING = 'CAROUSELGRAPHICS_LOADING';
export const CAROUSELGRAPHICS_FAILED = 'CAROUSELGRAPHICS_FAILED';
export const ADD_CAROUSELGRAPHICS = 'ADD_CAROUSELGRAPHICS';

export const FAQGRAPHICS_LOADING = 'FAQGRAPHICS_LOADING';
export const FAQGRAPHICS_FAILED = 'FAQGRAPHICS_FAILED';
export const ADD_FAQGRAPHICS = 'ADD_FAQGRAPHICS';

export const PHONEMODELS_LOADING = 'PHONEMODELS_LOADING';
export const PHONEMODELS_FAILED = 'PHONEMODELS_FAILED';
export const ADD_PHONEMODELS = 'ADD_PHONEMODELS';

export const NEWSGRAPHICS_LOADING = 'NEWSGRAPHICS_LOADING ';
export const NEWSGRAPHICS_FAILED = 'NEWSGRAPHICS_FAILED';
export const ADD_NEWSGRAPHICS = 'ADD_NEWSGRAPHICS';